// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopProductTotal
{
    public string ProductName { get; set; }

    public int ProductId { get; set; }

    public int? ProductCategoryId { get; set; }

    public string ProductDescription { get; set; }

    public decimal? ProductPrice { get; set; }

    public string Size { get; set; }

    public string Weight { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public bool? Discontinued { get; set; }

    public int? RemainingQuantity { get; set; }

    public int? SupplierId { get; set; }

    public virtual ShopProductCategory ProductCategory { get; set; }

    public virtual ICollection<ShopOrderDetailTable> ShopOrderDetailTable { get; set; } = new List<ShopOrderDetailTable>();

    public virtual ICollection<ShopProductImageTable> ShopProductImageTable { get; set; } = new List<ShopProductImageTable>();
}