// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjCatChaOnlineShop.Models;

public partial class ShopMemberInfo
{
    public int MemberId { get; set; }

    public string MemberAccount { get; set; }

    public string CharacterName { get; set; }

    public int? LevelId { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateTime? Birthday { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public int? CatCoinQuantity { get; set; }

    public int? LoyaltyPoints { get; set; }

    public DateTime? RegistrationTime { get; set; }

    public DateTime? LastLoginTime { get; set; }

    public int? FavoriteId { get; set; }

    public int? CheckinDayCount { get; set; }

    public virtual ICollection<ShopCommonAddressData> ShopCommonAddressData { get; set; } = new List<ShopCommonAddressData>();

    public virtual ICollection<ShopMemberCouponData> ShopMemberCouponData { get; set; } = new List<ShopMemberCouponData>();

    public virtual ICollection<ShopOrderTotalTable> ShopOrderTotalTable { get; set; } = new List<ShopOrderTotalTable>();
}